// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosxOoub_yyuXlpzca_HOI0uplzCpeV34',
    appId: '1:879278142644:web:c22477b2873cf46edcd3e1',
    messagingSenderId: '879278142644',
    projectId: 'doorunlock-eeaad',
    authDomain: 'doorunlock-eeaad.firebaseapp.com',
    storageBucket: 'doorunlock-eeaad.firebasestorage.app',
    measurementId: 'G-RP18J1HNEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJInpEc4bwZ8JXt_LFpqYnMlY5wJfEKPs',
    appId: '1:879278142644:android:ed8f8e3e08469456dcd3e1',
    messagingSenderId: '879278142644',
    projectId: 'doorunlock-eeaad',
    storageBucket: 'doorunlock-eeaad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXOl_EawiMaiTgzoucG0bjODiZNdL4Pbo',
    appId: '1:879278142644:ios:df45421995af5222dcd3e1',
    messagingSenderId: '879278142644',
    projectId: 'doorunlock-eeaad',
    storageBucket: 'doorunlock-eeaad.firebasestorage.app',
    iosBundleId: 'com.example.doorLock1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXOl_EawiMaiTgzoucG0bjODiZNdL4Pbo',
    appId: '1:879278142644:ios:df45421995af5222dcd3e1',
    messagingSenderId: '879278142644',
    projectId: 'doorunlock-eeaad',
    storageBucket: 'doorunlock-eeaad.firebasestorage.app',
    iosBundleId: 'com.example.doorLock1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDosxOoub_yyuXlpzca_HOI0uplzCpeV34',
    appId: '1:879278142644:web:3e18fc5e6ae54358dcd3e1',
    messagingSenderId: '879278142644',
    projectId: 'doorunlock-eeaad',
    authDomain: 'doorunlock-eeaad.firebaseapp.com',
    storageBucket: 'doorunlock-eeaad.firebasestorage.app',
    measurementId: 'G-6CHED07QY2',
  );
}
